### ISSUE TITLE
gui images empty

### ISSUE THREAD

**Issue by antoniosap** [blstuart/eniac-simulator#1]
i do:
go mod init example.com/eniac
cd src
./mkbins
cp eniac.linux_i386 eniac
./eniac

What went wrong ?

![empty_eniac](https://user-images.githubusercontent.com/2323966/115453954-817c6b00-a220-11eb-93b5-3f4f3104ec3b.png)

**Comment by blstuart** [comment]
Sounds like you may still be in the src directory when running the simulator.  It's a little fiddly about where it expects to find things.  You want to be in the top-level directory of the repo where images and programs are subdirectories under your current directory.  I should see what I can do about making it behave a little more intelligently when looking for the images and configuration files.

Hope that helps,
BLS

**Comment by antoniosap** [comment]
mv eniac ..
cd ..
 ./eniac

1 step forward. this happen on every button press.
![eniac_2](https://user-images.githubusercontent.com/2323966/115461774-19cb1d80-a22a-11eb-938a-010580e2a1b3.png)

**Comment by blstuart** [comment]
Hmm.  Very interesting.  The simulator itself and the GUI are two different processes and this is an error from the GUI process saying that the pipe between them is broken.  This suggests that the simulator process may have exited.  If you hide/close the GUI window are there any error messages showing in the terminal window where you started the simulator?  For some reason, I have never managed to get the GUI process to exit when the pipe closes.  So I always end up using ctrl-C to terminate, and it shuts down both processes.

**Comment by antoniosap** [comment]
now work.
